/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import excepciones.ClaveNoExisteException;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import negocios.AVL;
import negocios.ArbolBinarioBusqueda;
import negocios.ArbolMViasDeBusqueda;
import negocios.IArbolBusqueda;

/**
 *
 * @author Emanuel
 */
public class JFPresentacion extends javax.swing.JFrame {

    /**
     * Creates new form JFPresentacion
     */
    
    IArbolBusqueda<String,String> diccionario = new ArbolBinarioBusqueda();
    boolean cambio = true;
    
   
    
    public JFPresentacion() throws FileNotFoundException, IOException {
        File archivoPalabras = new File("C:\\Users\\Emanuel\\Desktop\\PROYECTOS ED2\\Proy1-INF310 SB. Gutierres Vasquez Emanuel\\Proyecto-Diccionario\\build\\classes\\datos\\Palabras.txt");
        File archivoSignificado = new File("C:\\Users\\Emanuel\\Desktop\\PROYECTOS ED2\\Proy1-INF310 SB. Gutierres Vasquez Emanuel\\Proyecto-Diccionario\\build\\classes\\datos\\Significado.txt");
        BufferedReader entradaDePalabras = new BufferedReader(new FileReader(archivoPalabras));
        BufferedReader entradaDeSignificados = new BufferedReader(new FileReader(archivoSignificado));
         String lecturaPalabras = entradaDePalabras.readLine();
        String lecturaSignificados = entradaDeSignificados.readLine();
        String lineaVacia = "";
        int cantidadDeRotaciones = 0;
        //RELLENAR EL ARBOL
        while(lecturaPalabras != null ){
            String palabra = null;
            String significado = "";
            //Palabras
            palabra = lecturaPalabras;
            lecturaPalabras = entradaDePalabras.readLine();
            
            //Significado
            while(!lineaVacia.equals(lecturaSignificados)){
                significado += lecturaSignificados + "\n";
                lecturaSignificados = entradaDeSignificados.readLine();
            }
            
            //Cargar
            diccionario.insertar(palabra, significado);
            lecturaPalabras = entradaDePalabras.readLine();
            lecturaSignificados = entradaDeSignificados.readLine();
        }
        
        
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEntradaBuscar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtEliminarPalabra = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtInsertarNuevoSinigicado = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtInsertarNuevaPalabra = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, 20, 10));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 660, 30, 10));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel3.setText("DICCIONARIO");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        txtEntradaBuscar.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jPanel1.add(txtEntradaBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 260, 30));

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 80, 30));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setEnabled(false);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 310, 150));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel4.setText("Significado");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arbol Binario De Busqueda", "AVL", "Arbol MVias De Busqueda" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        jLabel5.setText(" ******************************************  Modo Avanzado  ******************************************");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 830, 20));

        txtEliminarPalabra.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jPanel1.add(txtEliminarPalabra, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 430, 230, 30));

        txtInsertarNuevoSinigicado.setColumns(20);
        txtInsertarNuevoSinigicado.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        txtInsertarNuevoSinigicado.setRows(5);
        jScrollPane2.setViewportView(txtInsertarNuevoSinigicado);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 230, 140));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel6.setText("Eliminar Palabra");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 390, -1, -1));

        jButton2.setText("Insertar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 620, -1, -1));

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel7.setText("Palabra");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 430, -1, -1));

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel8.setText("Significado");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 500, -1, -1));

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel9.setText("Insertar Nueva Palabra");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));

        txtInsertarNuevaPalabra.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jPanel1.add(txtInsertarNuevaPalabra, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 230, 30));

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel10.setText("Palabra");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, -1, -1));

        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 470, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 833, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String palabraABuscar = txtEntradaBuscar.getText();
        String significado = diccionario.buscar(palabraABuscar);
        jTextArea1.setText(significado);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        
        List<String> claves = new LinkedList<>();
        List<String> valores = new LinkedList<>();
        if(cambio){
            claves = diccionario.recorridoEnInOrden();
            valores = diccionario.recorridoEnInOrdenV();
        } else {
            
            BufferedReader entradaDePalabras = null;
            try {
                File archivoPalabras = new File("C:\\Users\\Emanuel\\Desktop\\PROYECTOS ED2\\Proy1-INF310 SB. Gutierres Vasquez Emanuel\\Proyecto-Diccionario\\build\\classes\\datos\\Palabras.txt");
                File archivoSignificado = new File("C:\\Users\\Emanuel\\Desktop\\PROYECTOS ED2\\Proy1-INF310 SB. Gutierres Vasquez Emanuel\\Proyecto-Diccionario\\build\\classes\\datos\\Significado.txt");
                entradaDePalabras = new BufferedReader(new FileReader(archivoPalabras));
                BufferedReader entradaDeSignificados = new BufferedReader(new FileReader(archivoSignificado));
                String lecturaPalabras = entradaDePalabras.readLine();
                String lecturaSignificados = entradaDeSignificados.readLine();
                String lineaVacia = "";
                int cantidadDeRotaciones = 0;
                //RELLENAR EL ARBOL
                while(lecturaPalabras != null ){
                    String palabra = null;
                    String significado = "";
                    //Palabras
                    palabra = lecturaPalabras;
                    lecturaPalabras = entradaDePalabras.readLine();
                    
                    //Significado
                    while(!lineaVacia.equals(lecturaSignificados)){
                        significado += lecturaSignificados + "\n";
                        lecturaSignificados = entradaDeSignificados.readLine();
                    }
                    
                    //Cargar
                    //diccionario.insertar(palabra, significado);
                    claves.add(palabra);
                    valores.add(significado);
                    lecturaPalabras = entradaDePalabras.readLine();
                    lecturaSignificados = entradaDeSignificados.readLine();
                }   } catch (FileNotFoundException ex) {
                Logger.getLogger(JFPresentacion.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(JFPresentacion.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    entradaDePalabras.close();
                } catch (IOException ex) {
                    Logger.getLogger(JFPresentacion.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
        }
        
        if(jComboBox1.getSelectedItem().equals("Arbol Binario De Busqueda")){
            diccionario = new ArbolBinarioBusqueda<>();
            cambio = true;
        }
        if(jComboBox1.getSelectedItem().equals("AVL")){
            diccionario = new AVL<>();
            cambio = true;
        }
        if(jComboBox1.getSelectedItem().equals("Arbol MVias De Busqueda")){
            diccionario = new ArbolMViasDeBusqueda<>();
            cambio = false;
        }
        
        for (int i = 0; i < claves.size(); i++) {
            diccionario.insertar(claves.get(i), valores.get(i));
        }
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String palabra = txtInsertarNuevaPalabra.getText();
        String significado = txtInsertarNuevoSinigicado.getText();
        diccionario.insertar(palabra, significado);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String palabra = txtEliminarPalabra.getText();
        try {
            diccionario.eliminar(palabra);
        } catch (ClaveNoExisteException ex) {
            Logger.getLogger(JFPresentacion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPresentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPresentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPresentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPresentacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new JFPresentacion().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(JFPresentacion.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(JFPresentacion.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txtEliminarPalabra;
    private javax.swing.JTextField txtEntradaBuscar;
    private javax.swing.JTextField txtInsertarNuevaPalabra;
    private javax.swing.JTextArea txtInsertarNuevoSinigicado;
    // End of variables declaration//GEN-END:variables
}
